<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>dfd6dbc7-909e-4f4f-8955-7e78a38d1a3e</elementGuidId>
    <imagePath></imagePath>
    <name>h1_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/header[1]/h1[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>h1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>