<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>aded9c5f-5adb-412d-9823-108f66225bad</elementGuidId>
    <imagePath></imagePath>
    <name>link_facultyAndStaff</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/section[1]/nav[1]/ul[1]/li[2]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'https://www.stanford.edu/faculty-staff-gateway/') and equals(@text,'Faculty &amp; Staff')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:text=\"Faculty &amp; Staff\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>https://www.stanford.edu/faculty-staff-gateway/</value>
        <webElementGuid>1706720b-e6c2-4f0d-a2c1-2b7397fcf8c8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Faculty &amp; Staff</value>
        <webElementGuid>1706720b-e6c2-4f0d-a2c1-2b7397fcf8c8</webElementGuid>
    </webElementProperties>
</WebElementEntity>